[build]
  command = "npm run build"
  publish = "build"

[build.environment]
  NODE_VERSION = "24"
  REACT_APP_MEDIA_BASE_URL = "https://d39v3tn5ezy2mw.cloudfront.net/portfolio/v1"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
